apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: karteless
  name: pvc-karteless
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
#  storageClassName: gp2
  storageClassName: gp3-csi
  resources:
    requests:
#      storage: 1Mi
      storage: 2Gi

