apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range-karteless-poc
  namespace: dajp1-dxpf-cont-ocppro-karteless-poc
spec:
  limits:
  - default:
      memory: 100Mi
      cpu: 100m
    defaultRequest:
      memory: 100Mi
      cpu: 100m
    max:
      cpu: '2'
      memory: 4Gi
    min:
      cpu: 50m
      memory: 50Mi
    type: Container

